[[module]]
source = "modules/alacritty"
target = "~/.config/alacritty"

[[module]]
source = "modules/helix"
target = "~/.config/helix"

[[module]]
source = "modules/fish"
target = "~/.config/fish"

[[module]]
source = "modules/ags"
target = "~/.config/ags"

[[module]]
source = "modules/hypr"
target = "~/.config/hypr"
