[[module]]
source = "modules/helix"
target = "~/.config/helix"

[[module]]
source = "modules/fish"
target = "~/.config/fish"

[[module]]
source = "modules/ags"
target = "~/.config/ags"

[[module]]
source = "modules/iterm2"
target = "~/.config/iterm2"

[[module]]
source = "modules/nvim"
target = "~/.config/nvim"
